# Generated by Django 5.1.4 on 2024-12-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'контакт', 'verbose_name_plural': 'контакты'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
        migrations.AlterModelOptions(
            name='tradecompany',
            options={'ordering': ('name',), 'verbose_name': 'компания', 'verbose_name_plural': 'компании'},
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='торговая марка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_model',
            field=models.CharField(blank=True, help_text='введите модель', max_length=250, null=True, unique=True, verbose_name='название модели'),
        ),
        migrations.AlterField(
            model_name='product',
            name='release_date',
            field=models.DateField(blank=True, help_text='дата выпуска продукта в продажу', null=True, verbose_name='Дата выпуска продукта'),
        ),
    ]
