# Generated by Django 5.1.4 on 2024-12-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradecompany',
            name='creation_time',
            field=models.TimeField(auto_now_add=True, verbose_name='время создания'),
        ),
    ]
