# Generated by Django 5.1.4 on 2024-12-11 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_alter_contact_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradecompany',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='trade_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trade.tradecompany', verbose_name='компания'),
        ),
    ]
